name: MeinTest
on:
  push:
    branches:
    - master
    jobs:
      build:
      name: Starte Windows
      runs-on: windows-latest

      steps:
        - uses: actions/checkout@v1      
        - run:
          MSBuild.exe GITHUB_WORKSPACE\pp-p2p-import.sln
